import C_healthy
from C_healthy import *

bmi = BMI(70, 1.75)
bmr = BMR("male", 60, 1.75, 18)
tdee = TDEE("male", 60, 1.75, 18, 3)
lbm = LBM("male", 70, 1.75)
ffmi = FFMI("male", 60, 1.7)
rfm = RFM(85, 1.7)
bfp = BFP("male", 70, 1.75, 20)
ibw = IBW("male", 1.75)
whr = WHR("male", 85, 95)
bbw = BBW(60)
ma = MA("male", 70, 1.7, 18)
vfr = VFR(85, 95)
bsa = BSA(1.7, 60)
vo2max = VO2MAX(110, 60)
hsi = HSI("male", 60, 1.7, 18, 200, 110)
mmi = MMI("male", 60, 1.7)
bfm = BFM("male", 60, 1.7, 18)
absi = ABSI(85, 70, 1.75)
avi = AVI(85, 95)
bai = BAI(95, 1.75)
ci = CI(70, 1.75, 85)
whtr = WHtR(85, 1.75)
pi = PonderalIndex(70, 1.75)
fmi = FMI("male", 70, 1.75, 20)
ffm = FFM("male", 70, 1.75)
fmr = FMR("male", 70, 1.75, 20)
tbw = TBW("male", 70, 1.75, 20)
ecw = ECW("male", 70, 1.75, 20)
icw = ICW("male", 70, 1.75, 20)
bcm = BCM("male", 70, 1.75, 20)
smi = SMI("male", 70, 1.75)
asmi = ASMI("male", 70, 1.75)
mamc = MAMC(28.0, 12.0)
muac_assess = MUAC_Assessment("male", 28.0)
bee = BEE("male", 70, 1.75, 20)
ree = REE("male", 70, 1.75, 20)
pal = PAL("male", 70, 1.75, 20, 3)
met = MET(14.0)
mhr = MaxHeartRate(20)
hrr = HeartRateReserve(60, 20)
thr = TargetHeartRate(60, 20, 0.7)
cal_deficit = CalorieDeficit(2100.0, 500)
cal_surplus = CalorieSurplus(2100.0, 300)
p_need = ProteinNeed(70, "high") 
f_need = FatNeed(2100.0, 0.25)
c_need = CarbNeed(2100.0, p_need, f_need)
w_need = WaterNeed(70, 60)
ideal_w = IdealWater(70)
lbp = LeanBodyPercentage("male", 70, 1.75)
fp = FatPercentage("male", 70, 1.75, 20)
mp = MusclePercentage("male", 70, 1.75)
bm_est = BoneMassEstimate("male", 70, 1.75)
bmi_prime = BMIPrime(70, 1.75)
corp_idx = CorpulenceIndex(70, 1.75)
rfm_ext = RelativeFatMass_Ext("male", 85, 1.75)
bri = BodyRoundnessIndex(85, 1.75)
abri = ABodyRoundness(85, 1.75)
vai = VisceralAdiposityIndex("male", 70, 1.75, 85, 1.5, 1.2)
lap = LipidAccumulationProduct("male", 85, 1.5)
fat_mass = FatMass("male", 70, 1.75, 20)
lean_mass = LeanMass("male", 70, 1.75)

print("BMI:", bmi, "\nAdvice:", NABMI(bmi))
print("BMR:", bmr, "\nAdvice:", NABMR("male", bmr))
print("TDEE:", tdee, "\nAdvice:", NATDEE("male", tdee))
print("LBM:", lbm, "\nAdvice:", NALBM(lbm))
print("FFMI:", ffmi, "\nAdvice:", NAFFMI(ffmi))
print("RFM:", rfm, "\nAdvice:", NARFM(rfm))
print("BFP:", bfp, "\nAdvice:", NABFP(bfp))
print("IBW:", ibw, "\nAdvice:", NAIBW(ibw))
print("WHR:", whr, "\nAdvice:", NAWHR(whr))
print("BBW:", bbw, "\nAdvice:", NABBW(bbw))
print("MA:", ma, "\nAdvice:", NAMA(ma))
print("VFR:", vfr, "\nAdvice:", NAVFR(vfr))
print("BSA:", bsa, "\nAdvice:", NABSA(bsa))
print("VO2MAX:", vo2max, "\nAdvice:", NAVO2MAX(vo2max))
print("HSI:", hsi, "\nAdvice:", NAHSI(hsi))
print("MMI:", mmi, "\nAdvice:", NAMMI(mmi))
print("BFM:", bfm, "\nAdvice:", NABFM(bfm))
print("ABSI:", absi, "\nAdvice:", NAABSI(absi))
print("AVI:", avi, "\nAdvice:", NAAVI(avi))
print("BAI:", bai, "\nAdvice:", NABAI(bai))
print("CI:", ci, "\nAdvice:", NACI(ci))
print("WHtR:", whtr, "\nAdvice:", NAWHtR(whtr))
print("Ponderal Index:", pi, "\nAdvice:", NAPonderalIndex(pi))
print("FMI:", fmi, "\nAdvice:", NAFMI(fmi))
print("FFM:", ffm, "\nAdvice:", NAFFM(ffm))
print("FMR:", fmr, "\nAdvice:", NAFMR(fmr))
print("TBW:", tbw, "\nAdvice:", NATBW(tbw))
print("ECW:", ecw, "\nAdvice:", NAECW(ecw))
print("ICW:", icw, "\nAdvice:", NAICW(icw))
print("BCM:", bcm, "\nAdvice:", NABCM(bcm))
print("SMI:", smi, "\nAdvice:", NASMI(smi))
print("ASMI:", asmi, "\nAdvice:", NAASMI(asmi))
print("MAMC:", mamc, "\nAdvice:", NAMAMC(mamc))
print("MUAC Assessment:", muac_assess, "\nAdvice:", NAMUAC(muac_assess))
print("BEE:", bee, "\nAdvice:", NABEE(bee))
print("REE:", ree, "\nAdvice:", NAREE(ree))
print("PAL:", pal, "\nAdvice:", NAPAL(pal))
print("MET:", met, "\nAdvice:", NAMET(met))
print("Max HR:", mhr, "\nAdvice:", NAMaxHeartRate(mhr))
print("HRR:", hrr, "\nAdvice:", NAHeartRateReserve(hrr))
print("Target HR:", thr, "\nAdvice:", NATargetHeartRate(thr))
print("Calorie Deficit:", cal_deficit, "\nAdvice:", NACalorieDeficit(cal_deficit))
print("Calorie Surplus:", cal_surplus, "\nAdvice:", NACalorieSurplus(cal_surplus))
print("Protein Need:", p_need, "\nAdvice:", NAProteinNeed(p_need))
print("Fat Need:", f_need, "\nAdvice:", NAFatNeed(f_need))
print("Carb Need:", c_need, "\nAdvice:", NACarbNeed(c_need))
print("Water Need (w/ exercise):", w_need, "\nAdvice:", NAWaterNeed(w_need))
print("Ideal Water:", ideal_w, "\nAdvice:", NAIdealWater(ideal_w))
print("Lean Body Percentage:", lbp, "\nAdvice:", NALeanBodyPercentage(lbp))
print("Fat Percentage:", fp, "\nAdvice:", NAFatPercentage(fp))
print("Muscle Percentage:", mp, "\nAdvice:", NAMusclePercentage(mp))
print("Bone Mass Estimate:", bm_est, "\nAdvice:", NABoneMassEstimate(bm_est))
print("BMI Prime:", bmi_prime, "\nAdvice:", NABMIPrime(bmi_prime))
print("Corpulence Index:", corp_idx, "\nAdvice:", NACorpulenceIndex(corp_idx))
print("RFM Ext:", rfm_ext, "\nAdvice:", NARelativeFatMass(rfm_ext))
print("BRI:", bri, "\nAdvice:", NABodyRoundnessIndex(bri))
print("ABRI:", abri, "\nAdvice:", NAABodyRoundness(abri))
print("VAI:", vai, "\nAdvice:", NAVisceralAdiposityIndex(vai))
print("LAP:", lap, "\nAdvice:", NALipidAccumulationProduct(lap))
print("Fat Mass:", fat_mass, "\nAdvice:", NAFatMass(fat_mass))
print("Lean Mass:", lean_mass, "\nAdvice:", NALeanMass(lean_mass))

# Phiên bản 
print("C_healthy Version:", C_healthy.__version__)

# Nội dung hướng dẫn
#print(INSTRUCT())
